#! /bin/bash

# --- Install Manjaro ARM Minimal ---
# Update and upgrade system packages
#git clone --depth 1 https://gitlab.manjaro.org/manjaro-arm/applications/manjaro-arm-installer
#cd manjaro-arm-installer
#chmod +x manjaro-arm-installer
#sudo -s
#bash manjaro-arm-installer
# If any dependencies are missing, install them:
# 	bash, wget, git, systemd, dialog, parted, libarchive, binfmt-qemu-static, openssl, gawk, dosfstools, polkit

# --- Pre-Script Setup ---
#ip a
#sudo -s
#wpa_supplicant -B -i $WINTERFACE -c <(wpa_passphrase $SSID $PASSWORD)
#exit
#sudo pacman -S networkmanager git
#git clone --depth 1 https://github.com/andrevallestero/masars
#cd masars
#chmod a+x masars
#./masars

# --- MASARS Script ---
if [ "$EUID" -eq 0 ]; then
	echo 'This script should NOT be ran as root. Exiting.'
	exit 1
fi
#sudo sh -c 'echo "%wheel ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers'
pacman-mirrors
sudo pacman --noconfirm -S base-devel stow upower alsa-utils pulseaudio light bemenu-wayland foot sway neovim yay i3status-rust
cd ~
git clone --depth 1 https://github.com/AndreVallestero/manjaro-arm-sway-dotfiles.git
rm .bashrc .bash_profile .makepkg.conf
mkdir -p .config
cd manjaro-arm-sway-dotfiles
stow .
sudo rm -R ~/masars
sudo chmod a+w /sys/class/backlight/*/*
yay --noconfirm -S nerd-fonts-ubuntu-mono
#sudo sed -i '$ d' /etc/sudoers
echo 'MASARS complete, please reboot for all changes to take effect'
